spring.application.name=backend

# Configuration de la Base de Données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/juritn_db
spring.datasource.username=juritn_user
spring.datasource.password=juritn_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration Gemini IA (Model Stable w Jdid)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=YOUR_GEMINI_API_KEY_HERE